1. How many students demonstrate high academic engagement and performance?

SELECT
COUNT(*)
FROM STUDENT_DATA
WHERE ATTENDANCE_RATE>90
AND STUDY_HOURS_PER_WEEK>20
AND FINAL_EXAM_SCORE>85;

2. How does academic performance differ by gender?

SELECT
GENDER,
ROUND(AVG(AVERAGE_ASSIGNMENT_SCORE), 2) AS AVG_ASSIGN,
ROUND(AVG(MIDTERM_EXAM_SCORE), 2) AS MID_EXAM,
ROUND(AVG(FINAL_EXAM_SCORE), 2) AS FIN_EXAM
FROM STUDENT_DATA
GROUP BY GENDER
ORDER BY FIN_EXAM DESC;

3. What is the average attendance rate for each graduation outcome?

SELECT
GRADUATION_OUTCOME,
ROUND(AVG(ATTENDANCE_RATE), 2) AS ATTENDANCE_RATES
FROM STUDENT_DATA
GROUP BY GRADUATION_OUTCOME
ORDER BY ATTENDANCE_RATES DESC;

4. How many students fall into each attendance category?
Conditions:

Excellent (90+)
Good (75–89)
Poor (<75)

SELECT
CASE
    WHEN ATTENDANCE_RATE >= 90 THEN 'EXCELLENT'
    WHEN ATTENDANCE_RATE >= 75 AND ATTENDANCE_RATE < 90 THEN 'GOOD'
    WHEN ATTENDANCE_RATE < 75 THEN 'POOR'
END AS ATTENDANCE_CATEGORY,
COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT_DATA
GROUP BY
CASE
    WHEN ATTENDANCE_RATE >= 90 THEN 'EXCELLENT'
    WHEN ATTENDANCE_RATE >= 75 AND ATTENDANCE_RATE < 90 THEN 'GOOD'
    WHEN ATTENDANCE_RATE < 75 THEN 'POOR'
END;

5. What percentage of each gender is classified as dropout risk?

SELECT
GENDER,
ROUND(AVG(AVERAGE_ASSIGNMENT_SCORE), 2) AS AVERAGE_ASSIGNMENT_SCORE,
ROUND(AVG(MIDTERM_EXAM_SCORE), 2) AS AVERAGE_MIDTERM_SCORE,
ROUND(AVG(FINAL_EXAM_SCORE), 2) AS AVERAGE_FINAL_SCORE,
ROUND(
    COUNT(
        CASE
            WHEN GRADUATION_OUTCOME = 'DROPOUT_RISK'
            THEN 1
        END
    ) * 100.0 / COUNT(*),
    2
) AS DROP_OUT_RISK_PERCENTAGE
FROM STUDENT_DATA
GROUP BY GENDER;

6. Create a behavioural summary for each graduation outcome.

SELECT
GRADUATION_OUTCOME,
COUNT(*) AS TOTAL_STUDENTS,
ROUND(AVG(ATTENDANCE_RATE), 2) AS AVERAGE_ATTENDANCE,
ROUND(AVG(LMS_LOGINS_PER_WEEK), 2) AS AVERAGE_LMS_LOGINS,
ROUND(AVG(STUDY_HOURS_PER_WEEK), 2) AS AVERAGE_STUDY_HOURS,
ROUND(AVG(FINAL_EXAM_SCORE), 2) AS AVERAGE_FINAL_EXAM_SCORE
FROM STUDENT_DATA
GROUP BY GRADUATION_OUTCOME
ORDER BY AVERAGE_FINAL_EXAM_SCORE DESC;

7. Which students have unusually high study hours?

WITH STATS AS (
    SELECT
        AVG(STUDY_HOURS_PER_WEEK) AS AVG_STUDY_HOURS
    FROM STUDENT_DATA
)
SELECT
    STUDENT_ID,
    STUDY_HOURS_PER_WEEK
FROM STUDENT_DATA,
     STATS

WHERE STUDY_HOURS_PER_WEEK >
      (AVG_STUDY_HOURS * 2);

8. Generate summary statistics for a student's final exam score

SELECT
    MIN(FINAL_EXAM_SCORE) AS MIN_SCORE,
    MAX(FINAL_EXAM_SCORE) AS MAX_SCORE,
    ROUND(AVG(FINAL_EXAM_SCORE),2) AS AVG_SCORE
FROM STUDENT_DATA;


9. How many records belong to each graduation outcome?

SELECT
    GRADUATION_OUTCOME,
    COUNT(*) AS RECORD_COUNT
FROM STUDENT_DATA
GROUP BY GRADUATION_OUTCOME;
