Data Quality audits
1. Are there any missing values in critical analytical columns?

SELECT
    COUNT(CASE WHEN ATTENDANCE_RATE IS NULL THEN 1 END)
        AS MISSING_ATTENDANCE,
    COUNT(CASE WHEN FINAL_EXAM_SCORE IS NULL THEN 1 END)
        AS MISSING_FINAL_SCORE,
    COUNT(CASE WHEN GRADUATION_OUTCOME IS NULL THEN 1 END)
        AS MISSING_OUTCOME
FROM STUDENT_DATA;

2. Do any duplicate student IDs exist?

SELECT
    STUDENT_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM STUDENT_DATA
GROUP BY STUDENT_ID
HAVING COUNT(*) > 1;

3. Which students have unusually high study hours?

WITH STATS AS (
    SELECT
        AVG(STUDY_HOURS_PER_WEEK) AS AVG_STUDY_HOURS
    FROM STUDENT_DATA
)
SELECT
    STUDENT_ID,
    STUDY_HOURS_PER_WEEK
FROM STUDENT_DATA,
     STATS

WHERE STUDY_HOURS_PER_WEEK >
      (AVG_STUDY_HOURS * 2);

4. Generate summary statistics for a student's final exam score

SELECT
    MIN(FINAL_EXAM_SCORE) AS MIN_SCORE,
    MAX(FINAL_EXAM_SCORE) AS MAX_SCORE,
    ROUND(AVG(FINAL_EXAM_SCORE),2) AS AVG_SCORE
FROM STUDENT_DATA;

5. Create a table view for a machine learning pipeline

SELECT
    STUDENT_ID,
    ATTENDANCE_RATE,
    LMS_LOGINS_PER_WEEK,
    STUDY_HOURS_PER_WEEK,
    FINAL_EXAM_SCORE,
    CASE
        WHEN GRADUATION_OUTCOME = 'DROPOUT_RISK'
        THEN 1
        ELSE 0
    END AS TARGET_LABEL
FROM STUDENT_DATA;

6. How many records belong to each graduation outcome?

SELECT
    GRADUATION_OUTCOME,
    COUNT(*) AS RECORD_COUNT
FROM STUDENT_DATA
GROUP BY GRADUATION_OUTCOME;

7. Create a summary table at the graduation outcome level.

SELECT
    GRADUATION_OUTCOME,
    COUNT(*) AS TOTAL_STUDENTS,
    ROUND(AVG(ATTENDANCE_RATE),2) AS AVG_ATTENDANCE,
    ROUND(AVG(FINAL_EXAM_SCORE),2) AS AVG_FINAL_SCORE
FROM STUDENT_DATA
GROUP BY GRADUATION_OUTCOME;
